version: 0.2
phases:
  install:
    runtime-versions:
      httpd: latest
    on-failure: ABORT
  pre_build:
    commands:
      - echo on prebuild now
      - ls -lah
      - pwd
      - systemctl status httpd
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
